server {
    listen 80;
    listen [::]:80;
    server_name panss.duckdns.org;
    return 301 https://panss.dpdns.org$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name panss.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/panss.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/panss.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://panss.dpdns.org$request_uri;
}
